---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MRV.
--- DateTime: 16/12/2022 17:41
---

---@class CCFGPersonalMenu
local CFG <const> = {}

if IS_RDR3 then
    CFG.WalkingStyles = {
        {
            name = 'MP_Style_Default',
            label = 'Défaut'
        },

        {
            name = 'MP_Style_Casual',
            label = 'Décontractée'
        },

        {
            name = 'MP_Style_Crazy',
            label = 'Folle'
        },

        {
            name = 'MP_Style_Flamboyant',
            label = 'Flamboyante'
        },

        {
            name = 'MP_Style_Gunslinger',
            label = 'Pistolero'
        },

        {
            name = 'MP_Style_Refined',
            label = 'Raffinée'
        },

        {
            name = 'MP_Style_SilentType',
            label = 'Silencieuse'
        },

        {
            name = 'MP_Style_Greenhorn',
            label = 'Jeunot'
        },

        {
            name = 'MP_Style_Veteran',
            label = 'Vétéran'
        },

        {
            name = 'MP_Style_EasyRider',
            label = 'Easy Rider'
        }
    }
end

---@module CPersonalMenu : Module
local m = Modules.Get('personalmenu')
m:CFG(CFG)