---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MRV.
--- DateTime: 10/12/2022 19:29
---

---@module CPersonalMenu
local m = iAm('personalmenu')

m:OnStart(function()
    m.CreatePersonalMenu()

    if IS_GTA5 then
        GAME.RegisterControl('personal_menu', 'Menu personnel', { 'keyboard', 'f5' }, nil, m.OpenPersonalMenu, nil)
    elseif IS_RDR3 then
        GAME.RegisterControlHandler(0, `INPUT_SELECT_ITEM_WHEEL`, false, m.OpenPersonalMenu)
    end
end)

local function startTemporaryAccountNotification()
    if not CPlayer.IsTemporaryAccount() then return end

    local timeoutMs = 30 * 60 * 1000

    IMPOSTEUR.SetTimeout(timeoutMs, function()
        if not CPlayer.IsTemporaryAccount() then return end

        local msg = ('Vous utilisez un ~r~compte temporaire~s~ et risquez de ~r~perdre votre progression~s~, pour éviter cela ~b~créez un compte permanent~s~ (F5 -> Compte) et obtenez ~y~%s %s~s~ offert en boutique !'):format(
            IMPOSTEUR.LocalizeShopToken(GlobalCFG.PermanentAccountShopTokensReward),
            IMPOSTEUR.GetLocalizedShopTokenName()
        )

        GAME.Notification(msg)

        startTemporaryAccountNotification()
    end)
end

-- TODO: Also check if addon group has been added while connected
IMPOSTEUR.On('playerSpawned', function(spawn, firstSpawn)
    if not firstSpawn then
        return
    end

    startTemporaryAccountNotification()

    if not CPlayer.IsInAddonGroup('vip') then
        return
    end

    m.AddVipMenu()
end)