--╔════════════════════════════════════════════════════════════════════════════════╗

-- ██████╗ ██╗ ██████╗████████╗██╗   ██╗██████╗ ███████╗███████╗
-- ██╔══██╗██║██╔════╝╚══██╔══╝██║   ██║██╔══██╗██╔════╝██╔════╝
-- ██████╔╝██║██║        ██║   ██║   ██║██████╔╝█████╗  ███████╗
-- ██╔═══╝ ██║██║        ██║   ██║   ██║██╔══██╗██╔══╝  ╚════██║
-- ██║     ██║╚██████╗   ██║   ╚██████╔╝██║  ██║███████╗███████║
-- ╚═╝     ╚═╝ ╚═════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════╝
                                                             

Config.Pictures = {
    -- cash
    ['money'] = 'assets/images/money.png',
    ['black_money'] = 'assets/images/black_money.png',
    -- id card
    ['id'] = 'assets/images/id_card.png',
    ['weapon'] = 'assets/images/weaponlicense.png',
    ['drive'] = 'assets/images/driver_license.png',
    ['police'] = 'assets/images/badge-lspd2.png',
    -- food
    ['water'] = 'assets/images/np_water.png',
    ['coca'] = 'assets/images/coca.png',
    ['burger'] = 'assets/images/burger.png',
    ['casino_burger'] = 'assets/images/burger.png',
    ['beer'] = 'assets/images/beer.png',
    ['tomato'] = 'assets/images/tomato.png',
    ['whisky'] = 'assets/images/whisky.png',
    ['cafe'] = 'assets/images/cafe.png',
    ['bread'] = 'assets/images/bread.png',
    ['vodka'] = 'assets/images/vodka.png',
    ['np_water'] = 'assets/images/np_water.png',
    ['hotdog'] = 'assets/images/np_hotdog',
    ['jagerbomb'] = 'assets/images/jager.png',
    -- drugs
    ['weed'] = 'assets/images/weedq.png',
    ['weed_pooch'] = 'assets/images/weed_pooch.png',
    ['cocaine'] = 'assets/images/weedq.png',
    ['cocainetraitement'] = 'assets/images/np_cocaine-baggy.png',
    ['cocaine_packaged'] = 'assets/images/cocaine_packaged.png',
    ['meth'] = 'assets/images/weedq.png',
    ['meth_pooch'] = 'assets/images/np_meth-bagg.png',
    ['opium'] = 'assets/images/weedq.png',
    ['opium_pooch'] = 'assets/images/weed-4-Oz.png',
    -- objets
    ['armor'] = 'assets/images/gillet.png',
    ['armor391'] = 'assets/images/armor.png',
    ['armor390'] = 'assets/images/armor.png',
    ['armor392'] = 'assets/images/armor.png',
    ['bandage'] = 'assets/images/bandage.png',
    ['bankcard'] = 'assets/images/bankcard.png',
    ['bag'] = 'assets/images/bag.png',
    ['phone'] = 'assets/images/phone.png',
    ['bijoux'] = 'assets/images/jewels.png',
    ['jewels'] = 'assets/images/jewels.png',
    ['radio'] = 'assets/images/radio.png',
    ['fixkit'] = 'assets/images/fixkit.png',
    ['computercrack'] = 'assets/images/computercrack.png',
    ['jumelle'] = 'assets/images/jumelle.png',
    ['medikit'] = 'assets/images/np_medbag.png',
    ['boombox'] = 'assets/images/boombox.png',
    ['drill'] = 'assets/images/np_drill.png',
    ['radio'] = 'assets/images/np_radio.png',
    ['bois'] = 'assets/images/wood.png',
    -- clothe
    ['pants'] = 'assets/images/pants.png',
    ['top'] = 'assets/images/top.png',
    ['shoes'] = 'assets/images/shoes.png',
    ['helmet'] = 'assets/images/hat.png',
    ['glasses'] = 'assets/images/glasses.png',
    ['outfit'] = 'assets/images/tenue.png',
    ['mask'] = 'assets/images/mask.png',
    ['bags'] = 'assets/images/bags.png',
    ['watches'] = 'assets/images/clothes_montre.png',
    ['ears'] = 'assets/images/clothes_earring.png',
    ['chain'] = 'assets/images/clothes_chaine.png',
    -- rcore camping
    ['gazebo_3'] = 'assets/images/gazebo_3.png',
    ['gazebo_1'] = 'assets/images/gazebo_1.png',
    ['gazebo_2'] = 'assets/images/gazebo_2.png',
    ['chair_3'] = 'assets/images/chair_3.png',
    ['chair_2'] = 'assets/images/chair_2.png',
    ['chair_1'] = 'assets/images/chair_1.png',
    ['tent_2'] = 'assets/images/tent_2.png',
    ['tent_1'] = 'assets/images/tent_1.png',
    ['wood'] = 'assets/images/wood.png',
    ['beerkeg'] = 'assets/images/beerkeg.png',
    ['raw_chicken'] = 'assets/images/raw_chicken.png',
    ['cooked_chicken'] = 'assets/images/cooked_chicken.png',
    ['fireplace'] = 'assets/images/fireplace.png',
    -- weapon
    ['chargeur'] = 'assets/images/clip.png',
    ['clip'] = 'assets/images/arAmmo.png',
    ['WEAPON_ASSAULTRIFLE'] = 'assets/images/weapon_assaultrifle.png',
    ['WEAPON_CARBINERIFLE'] = 'assets/images/weapon_carbinerifle.png',
    ['WEAPON_ADVANCEDRIFLE'] = 'assets/images/weapon_advancedrifle.png',
    ['WEAPON_ASSAULTSHOTGUN'] = 'assets/images/weapon_assaultshotgun.png',
    ['WEAPON_ASSAULTSMG'] = 'assets/images/weapon_assaultsmg.png',
    ['WEAPON_BAT'] = 'assets/images/weapon_bat.png',
    ['WEAPON_BATTLEAXE'] = 'assets/images/weapon_battleaxe.png',
    ['WEAPON_BOTTLE'] = 'assets/images/weapon_bottle.png',
    ['WEAPON_CERAMICPISTOL'] = 'assets/images/weapon_ceramicpistol.png',
    ['WEAPON_COMBATPDW'] = 'assets/images/weapon_combatpdw.png',
    ['WEAPON_COMBATPISTOL'] = 'assets/images/weapon_combatpistol.png',
    ['WEAPON_COMPACTRIFLE'] = 'assets/images/weapon_compactrifle.png',
    ['WEAPON_CROWBAR'] = 'assets/images/weapon_crowbar.png',
    ['WEAPON_DAGGER'] = 'assets/images/weapon_dagger.png',
    ['WEAPON_KNUCKLE'] = 'assets/images/weapon_knuckle.png',
    ['WEAPON_FLASHLIGHT'] = 'assets/images/weapon_flashlight.png',
    ['WEAPON_GOLFCLUB'] = 'assets/images/weapon_golfclub.png',
    ['WEAPON_HAMMER'] = 'assets/images/weapon_hammer.png',
    ['WEAPON_HATCHET'] = 'assets/images/weapon_hatchet.png',
    ['WEAPON_HEAVYPISTOL'] = 'assets/images/weapon_heavypistol.png',
    ['WEAPON_KNIFE'] = 'assets/images/weapon_knife.png',
    ['WEAPON_MACHETE'] = 'assets/images/weapon_machete.png',
    ['WEAPON_MACHINEPISTOL'] = 'assets/images/weapon_machinepistol.png',
    ['WEAPON_MICROSMG'] = 'assets/images/weapon_microsmg.png',
    ['WEAPON_MILITARYRIFLE'] = 'assets/images/weapon_militaryrifle.png',
    ['WEAPON_MINISMG'] = 'assets/images/weapon_minismg.png',
    ['WEAPON_MUSKET'] = 'assets/images/weapon_musket.png',
    ['WEAPON_NIGHTSTICK'] = 'assets/images/weapon_nightstick.png',
    ['WEAPON_PETROLCAN'] = 'assets/images/weapon_petrolcan.png',
    ['WEAPON_REVOLVER'] = 'assets/images/weapon_revolver.png',
    ['weapon_pistol'] = 'assets/images/weapon_pistol.png',
    ['WEAPON_PISTOL_MK2'] = 'assets/images/weapon_pistol_mk2.png',
    ['WEAPON_PISTOL50'] = 'assets/images/weapon_pistol50.png',
    ['WEAPON_POOLCUE'] = 'assets/images/weapon_poolcue.png',
    ['WEAPON_PUMPSHOTGUN'] = 'assets/images/weapon_pumpshotgun.png',
    ['WEAPON_SAWNOFFSHOTGUN'] = 'assets/images/weapon_sawnoffshotgun.png',
    ['WEAPON_SPECIALCARBINE'] = 'assets/images/weapon_specialcarbine.png',
    ['WEAPON_STUNGUN'] = 'assets/images/weapon_stungun.png',
    ['WEAPON_SMG'] = 'assets/images/weapon_smg.png',
    ['WEAPON_SMG_MK2'] = 'assets/images/weapon_smg_mk2.png',
    ['WEAPON_SNSPISTOL'] = 'assets/images/weapon_snspistol.png',
    ['WEAPON_SNSPISTOL_MK2'] = 'assets/images/weapon_snspistol_mk2.png',
    ['WEAPON_SWITCHBLADE'] = 'assets/images/weapon_switchblade.png',
    ['WEAPON_HEAVYSNIPER'] = 'assets/images/WEAPON_HEAVYSNIPER.png',
    ['WEAPON_HEAVYSNIPER_MK2'] = 'assets/images/WEAPON_HEAVYSNIPER_MK2.png',
    ['WEAPON_WRENCH'] = 'assets/images/weapon_wrench.png',
    ['WEAPON_KATANA'] = 'assets/images/np_katana.png',
    ['WEAPON_HKUMP'] = 'assets/images/hkump.png',
    -- Farm
    ['acierrecolte'] = 'assets/images/steel.png',
    ['aciertraitement'] = 'assets/images/steel_bar.png',
}

--╚════════════════════════════════════════════════════════════════════════════════╝